/**
 * Core domain types.
 *
 * Conventions that apply everywhere:
 *  - All timestamps are epoch milliseconds (number), never `Date`. IndexedDB
 *    indexes numbers reliably and sorts them correctly; structured-cloned
 *    `Date` objects are indexable but comparing them across the boundary is a
 *    pit of small surprises. Conversion to `Date` happens only at the ts-fsrs
 *    call site, which accepts `DateInput` (number) anyway.
 *  - All ids are UUID strings generated by `newId()`.
 *  - Deletion of notes/cards is *soft* (`deletedAt`). Review history is
 *    expensive to recreate and impossible to recover; a typo fix must never
 *    destroy it.
 */

import type { State } from 'ts-fsrs';

/** Epoch milliseconds. */
export type Millis = number;

// ---------------------------------------------------------------------------
// Deck
// ---------------------------------------------------------------------------

export interface DeckConfig {
  /** New cards introduced per day. 0 disables new cards. */
  newPerDay: number;
  /** Maximum reviews per day. 0 means unlimited. */
  reviewsPerDay: number;
  /**
   * Hour (0-23, local time) at which the study day rolls over. Anki uses 4am
   * so that a late-night session still counts as the previous day.
   */
  rolloverHour: number;
  /** Per-deck FSRS overrides; unset fields fall back to the global params. */
  fsrs?: Partial<FsrsParams>;
}

export interface Deck {
  id: string;
  name: string;
  description: string;
  config: DeckConfig;
  created: Millis;
  modified: Millis;
}

export const DEFAULT_DECK_CONFIG: DeckConfig = {
  newPerDay: 20,
  reviewsPerDay: 200,
  rolloverHour: 4,
};

// ---------------------------------------------------------------------------
// Note
// ---------------------------------------------------------------------------

/**
 * A note is the authored unit. A **cloze** note is one block of text containing
 * `{{c1::...}}` markup and generates one card per distinct ordinal; a **basic**
 * note is a front and a back, and generates one card (or two, reversed).
 *
 * `type` is optional and absent means cloze — which is what every note written
 * before basic notes existed is. That keeps the addition free of a schema
 * migration and lets older backups import unchanged.
 *
 * Which cards a note generates lives in `src/notetypes.ts`, not here.
 */
export interface Note {
  id: string;
  deckId: string;
  /** Absent means `'cloze'`. */
  type?: 'cloze' | 'basic';
  /**
   * Cloze: the full text, including markup and `![](media:<id>)` references.
   * Basic: the front.
   */
  text: string;
  /** Basic only: the back. */
  back?: string;
  /** Basic only: also generate the back→front card. */
  reverse?: boolean;
  /** Optional context shown after the answer is revealed. */
  extra: string;
  tags: string[];
  /**
   * Stable hash of the normalized text, used for import de-duplication.
   * Computed by `hashNoteText()`.
   */
  contentHash: string;
  created: Millis;
  modified: Millis;
  /** Soft-delete marker. */
  deletedAt?: Millis;
}

// ---------------------------------------------------------------------------
// Card
// ---------------------------------------------------------------------------

/**
 * One card per cloze ordinal per note. Scheduling state mirrors ts-fsrs's
 * `Card` shape, with dates flattened to epoch millis and names camelCased.
 *
 * `elapsedDays` / `lastElapsedDays` are deprecated in ts-fsrs 6 but still
 * required by the v5 types; keep them stored so the upgrade is a no-op.
 */
export interface Card {
  id: string;
  noteId: string;
  /** Denormalized from the note so the due-queue query can use [deckId+due]. */
  deckId: string;
  /** The cloze ordinal this card tests: 1 for `{{c1::...}}`, etc. */
  ordinal: number;

  // --- FSRS state ---
  due: Millis;
  stability: number;
  difficulty: number;
  elapsedDays: number;
  scheduledDays: number;
  learningSteps: number;
  reps: number;
  lapses: number;
  state: State;
  lastReview?: Millis;

  /** Suspended cards never enter the queue but keep their state. */
  suspended: boolean;
  created: Millis;
  /** Soft-delete marker; set when the note no longer has this ordinal. */
  deletedAt?: Millis;
}

// ---------------------------------------------------------------------------
// Review log
// ---------------------------------------------------------------------------

/**
 * Append-only. Written on every answer, never mutated. Feeds the stats views
 * and is the training input for FSRS parameter optimization — if it isn't
 * captured from day one, it can never be reconstructed.
 */
export interface ReviewLog {
  id: string;
  cardId: string;
  deckId: string;
  /** 1=Again 2=Hard 3=Good 4=Easy (ts-fsrs `Rating`). */
  rating: number;
  /** Card state *before* this review. */
  state: State;
  due: Millis;
  stability: number;
  difficulty: number;
  elapsedDays: number;
  lastElapsedDays: number;
  scheduledDays: number;
  learningSteps: number;
  /** When the answer was given. */
  reviewedAt: Millis;
  /** Milliseconds spent on the card, for stats. */
  durationMs?: number;
}

// ---------------------------------------------------------------------------
// Media
// ---------------------------------------------------------------------------

export interface MediaItem {
  id: string;
  blob: Blob;
  filename: string;
  mime: string;
  size: number;
  /** SHA-256 of the bytes, for de-duplication on paste and import. */
  sha256: string;
  created: Millis;
}

// ---------------------------------------------------------------------------
// Meta / settings
// ---------------------------------------------------------------------------

export interface FsrsParams {
  requestRetention: number;
  maximumInterval: number;
  enableFuzz: boolean;
  enableShortTerm: boolean;
  learningSteps: string[];
  relearningSteps: string[];
  /** Trained weights; empty means "use the library defaults". */
  w: number[];
  /** When `w` was last fitted by the optimizer. Absent for defaults. */
  optimizedAt?: Millis;
}

export const DEFAULT_FSRS_PARAMS: FsrsParams = {
  requestRetention: 0.9,
  maximumInterval: 36500,
  enableFuzz: true,
  enableShortTerm: true,
  learningSteps: ['1m', '10m'],
  relearningSteps: ['10m'],
  w: [],
};

export interface Settings {
  theme: 'light' | 'dark' | 'system';
  /** Global rollover hour; decks may override. */
  rolloverHour: number;
  /** Remind about a backup after this many days without one. 0 disables. */
  backupReminderDays: number;
  lastBackupAt?: Millis;
  /** Result of the last `navigator.storage.persist()` request. */
  storagePersisted?: boolean;
}

export const DEFAULT_SETTINGS: Settings = {
  theme: 'system',
  rolloverHour: 4,
  backupReminderDays: 7,
};

/**
 * Settings that follow you across devices when sync is on. Everything else in
 * `Settings` belongs to the device: the theme you want on a phone isn't the
 * one you want on a laptop, and storage persistence is a per-browser grant.
 */
export const SYNCED_SETTING_KEYS = ['rolloverHour', 'backupReminderDays', 'lastBackupAt'] as const;
export type SyncedSettings = Pick<Settings, (typeof SYNCED_SETTING_KEYS)[number]>;

/**
 * The synced half of app state, in the `profile` table.
 *
 * Two rows, not one, so that changing a setting on one device and applying
 * fitted FSRS weights on another can't overwrite each other: each row is only
 * ever written whole, and they're written independently.
 *
 * The `#` prefix makes these *private ids* under Dexie Cloud: each user gets
 * their own `#settings` and `#fsrs`, rather than all users colliding on one
 * key. Without sync they're just ordinary string keys.
 */
export const PROFILE_SETTINGS_ID = '#settings' as const;
export const PROFILE_FSRS_ID = '#fsrs' as const;

export interface ProfileRow {
  id: typeof PROFILE_SETTINGS_ID | typeof PROFILE_FSRS_ID;
  /** On the `#settings` row. */
  settings?: Partial<SyncedSettings>;
  /** On the `#fsrs` row. */
  fsrsParams?: FsrsParams;
  modified: Millis;
}

/**
 * Single-row table holding this device's app state. Always keyed `'app'`.
 * Never synced. Its `settings` and `fsrsParams` are also the fallback for
 * data written before the `profile` table existed.
 */
export interface Meta {
  key: 'app';
  schemaVersion: number;
  settings: Settings;
  fsrsParams: FsrsParams;
  created: Millis;
  modified: Millis;
}

export const META_KEY = 'app' as const;
